/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as BasesDatosRouteImport } from './routes/bases-datos'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as DesplegarRouteImport } from './routes/desplegar'
import { Route as HistorialRouteImport } from './routes/historial'
import { Route as PerfilesIndexRouteImport } from './routes/perfiles/index'
import { Route as PerfilesProfileIdRouteImport } from './routes/perfiles/$profileId'
import { Route as PerfilesNuevoRouteImport } from './routes/perfiles/nuevo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const BasesDatosRoute = BasesDatosRouteImport.update({
  id: '/bases-datos',
  path: '/bases-datos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const DesplegarRoute = DesplegarRouteImport.update({
  id: '/desplegar',
  path: '/desplegar',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorialRoute = HistorialRouteImport.update({
  id: '/historial',
  path: '/historial',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilesIndexRoute = PerfilesIndexRouteImport.update({
  id: '/perfiles/',
  path: '/perfiles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilesProfileIdRoute = PerfilesProfileIdRouteImport.update({
  id: '/perfiles/$profileId',
  path: '/perfiles/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilesNuevoRoute = PerfilesNuevoRouteImport.update({
  id: '/perfiles/nuevo',
  path: '/perfiles/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/bases-datos': typeof BasesDatosRoute
  '/configuracion': typeof ConfiguracionRoute
  '/desplegar': typeof DesplegarRoute
  '/historial': typeof HistorialRoute
  '/perfiles/$profileId': typeof PerfilesProfileIdRoute
  '/perfiles/nuevo': typeof PerfilesNuevoRoute
  '/perfiles/': typeof PerfilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/bases-datos': typeof BasesDatosRoute
  '/configuracion': typeof ConfiguracionRoute
  '/desplegar': typeof DesplegarRoute
  '/historial': typeof HistorialRoute
  '/perfiles/$profileId': typeof PerfilesProfileIdRoute
  '/perfiles/nuevo': typeof PerfilesNuevoRoute
  '/perfiles': typeof PerfilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backups': typeof BackupsRoute
  '/bases-datos': typeof BasesDatosRoute
  '/configuracion': typeof ConfiguracionRoute
  '/desplegar': typeof DesplegarRoute
  '/historial': typeof HistorialRoute
  '/perfiles/$profileId': typeof PerfilesProfileIdRoute
  '/perfiles/nuevo': typeof PerfilesNuevoRoute
  '/perfiles/': typeof PerfilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backups'
    | '/bases-datos'
    | '/configuracion'
    | '/desplegar'
    | '/historial'
    | '/perfiles/$profileId'
    | '/perfiles/nuevo'
    | '/perfiles/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backups'
    | '/bases-datos'
    | '/configuracion'
    | '/desplegar'
    | '/historial'
    | '/perfiles/$profileId'
    | '/perfiles/nuevo'
    | '/perfiles'
  id:
    | '__root__'
    | '/'
    | '/backups'
    | '/bases-datos'
    | '/configuracion'
    | '/desplegar'
    | '/historial'
    | '/perfiles/$profileId'
    | '/perfiles/nuevo'
    | '/perfiles/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackupsRoute: typeof BackupsRoute
  BasesDatosRoute: typeof BasesDatosRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DesplegarRoute: typeof DesplegarRoute
  HistorialRoute: typeof HistorialRoute
  PerfilesProfileIdRoute: typeof PerfilesProfileIdRoute
  PerfilesNuevoRoute: typeof PerfilesNuevoRoute
  PerfilesIndexRoute: typeof PerfilesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bases-datos': {
      id: '/bases-datos'
      path: '/bases-datos'
      fullPath: '/bases-datos'
      preLoaderRoute: typeof BasesDatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desplegar': {
      id: '/desplegar'
      path: '/desplegar'
      fullPath: '/desplegar'
      preLoaderRoute: typeof DesplegarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historial': {
      id: '/historial'
      path: '/historial'
      fullPath: '/historial'
      preLoaderRoute: typeof HistorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfiles/': {
      id: '/perfiles/'
      path: '/perfiles'
      fullPath: '/perfiles/'
      preLoaderRoute: typeof PerfilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfiles/$profileId': {
      id: '/perfiles/$profileId'
      path: '/perfiles/$profileId'
      fullPath: '/perfiles/$profileId'
      preLoaderRoute: typeof PerfilesProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfiles/nuevo': {
      id: '/perfiles/nuevo'
      path: '/perfiles/nuevo'
      fullPath: '/perfiles/nuevo'
      preLoaderRoute: typeof PerfilesNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackupsRoute: BackupsRoute,
  BasesDatosRoute: BasesDatosRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DesplegarRoute: DesplegarRoute,
  HistorialRoute: HistorialRoute,
  PerfilesProfileIdRoute: PerfilesProfileIdRoute,
  PerfilesNuevoRoute: PerfilesNuevoRoute,
  PerfilesIndexRoute: PerfilesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
